version: '3.8'

services:
  ai-coding-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - CORS_ORIGIN=http://localhost:3000,http://localhost:5173
      - WORKSPACE_DIR=/app/workspace
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-your-dev-secret-key}
      - MAX_FILE_SIZE=10485760
    volumes:
      - ./workspace:/app/workspace
      - ./logs:/app/logs
    networks:
      - ai-coding-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Для продакшена можно добавить Redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - ai-coding-network
  #   restart: unless-stopped

  # Для мониторинга можно добавить Prometheus + Grafana
  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - ai-coding-network

networks:
  ai-coding-network:
    driver: bridge

volumes:
  redis_data:
    driver: local 