#!/bin/bash
echo 'Starting AI Coding Platform with Live File Watcher...'
echo 'Backend: File watcher with chokidar + WebSocket'
echo 'Frontend: Monaco Editor + Real-time updates'
echo ''
echo 'To start the system:'
echo '1. Backend: cd backend && npm start'
echo '2. Frontend: cd frontend && npm run dev'
echo '3. Navigate to http://localhost:5173/project/demo'
echo ''
echo 'Features implemented:'
echo '- Real-time file system monitoring'
echo '- WebSocket-based file events'
echo '- Monaco Editor with syntax highlighting'
echo '- File explorer with tree view'
echo '- Live updates on file changes'
echo '- File operations (create, delete, rename)'
echo '- Auto-save functionality'
echo '- Dark theme UI'
echo ''
echo 'File watcher will monitor: /home/user/Agiens_hackathon_vibecode'
echo 'WebSocket endpoints: ws://localhost:3000/ws?type=files'
echo 'API endpoints: http://localhost:3000/api/files/*'

